jdk:
  - openjdk15
before_install:
  - bash ensure-java-15 install
install:
  - if ! bash ensure-java-15 use; then source ~/.sdkman/bin/sdkman-init.sh; fi
  - java -version
  - mvn install -DskipTests