language: java
os: linux
dist: xenial
sudo: false
jdk:
- openjdk-ea
script: mvn clean verify
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: eZjtbyof3Bew6+25/tYcTSY5lclY6zVeZEwUUDWNvIyaMahqBqsqcLibI+ZmPwRiCETUaqyL2uzwVeskUlvaF8iMUd4wcb+kHpwzcKClQYAtXC4NUIHPOiGxs8KuaJ7y9UrxyvsyBK9qjCQb+NFI9IebX9Bxe8KfkOcWLStc1QUOuSe/ULH7lMmstdBE7AUwJ01CuNW5jK9IXFXRioybWnhnIIT2l0QfVzHRhZnXg8GhDk/ODV/9GssNntzUOuoYVZPxDCAEcvk3U2Z95iX4RZbLuNMURFSeyuJy4BRjgtnBkoDic3uKYFmcpzMAbzLL9okoK5wHaBFtASW6cTdAelGf2//qyvD5OMihgZwSlvOravhzMnupSP2ZiYOmKv3Hou2GSJ0AQPq8zWrMyrQdP7O5gXaS2dsltNlKljaM7YZ5Ge2lPdIliK2CvfVYuobQny4wEYuTbXlLs0tncqIMDwi1kFPzoHhQlexQv95hO7zL4X0jkXaZdhurGWbMu2JAXADycF2xBJhh/9RuSMfiSGTrx0Alky3yITOh9kKjwe02S3W4aFpgFuGshGFvMrEzln+Bybeg5CpPOil2j2DC3yHIEmsRMiysdnkJj7z3emo2EKPrkvO1vEbTwQLyp7DtEk8jWo6BsVgjIWbfPDiOiMygJ0lg1vg+eKzHQHHmMR4=
  - secure: KS11hln5zheY4Bhgw20fiMl6YLNPzhaEPJgENdKyMmU1CB9xlEXgDi3obw0Zc2GMuJMaC4v0R958jBTuq0Q+Yb5FNpVTXuTugaEJxw1mypuj/her3n/SM8hPu0yl1d+cxT9ZxY+a7EyKrGf5GA6zOHgmqU2Zd4cgo0SLcfK3qnBJp+0hSSxMxja2R64MNPKyhpyvomAg0BsThmT+f2FA8UHDLvMjfRLpw+2rRzvilAXwYCgy/Kbh3Wx6KtAVt5Ro4zLfvkFVtg5gHUks943U+bjEexNb3zfhyYJU9yX0fBYj45NglXrq5wrYLG08p9DmT1nfnDFV2JT9dA+diN/rB+NQ4I2CkEp6Hegn6nF6LrN8MVFby0q2vrmR8RdFGXsFvK/3auRa8HppfEEDFSMIocjWqOEIChXk0krZXNzuQV8dJBspaenuI9Tz/dW2cvbB7arWiMcR0wngcyYUuIHYzlVRETXA0HMg/cxuypf5IVqXOyTZcU/Sg8PZyuSx1jYH070aMualWBfk+1RhZwL3PRtQ2hB/lYMNC4/pKxxFygNW1GOLtNByV4DI0YxhtXQ+UdTUzioEObBakP2GDhHApWVBv4l/Vv7d+PnNwA0y4v+YsfkRqHqA1suUp9ArY99LoB3Mpp3MDhJfSS0KMjVbTDJtSAEppsnKR8EQadTRtFg=
